### ISSUE TITLE
skipgram and cbow model error definition

### ISSUE THREAD

**Issue by wanghao2020** [ixlan/word2vec-Theano#1]
ixlan:
    hi , I am glad to find you word2vec-theano in Github, But I have some questions about calculating the errors of the batch datasets in  skipgram.py and cbow.py, 
for the  cbow.py:
`neg_scores = T.nnet.sigmoid(T.sum(- T.tile(H, (self.nr_neg_samples, 1)) * self.W[neg_samples], axis=1))`
for the skipgram.py:
`H = T.tile(H, (self.nr_neg_samples, 1)) `
I think it shoud use the `repeat()`function instead of the `tile()`function for the batch datasets. It is right for only one sample, but for the batch samples, it is wrong for calculating the batch errors.

Looking forward to your reply！

Wish you Well！

**Comment by ixlan** [comment]
Hello !
Thank you very much for the report! This indeed is a bug, I’ve made a modification.
Arthur
